# Generated by Django 4.2 on 2023-04-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_posts_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="id",
            field=models.CharField(
                default="d9cc8fe951b549cba973aa705bf529df",
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
