# Generated by Django 4.2 on 2023-04-21 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_posts_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
