# Generated by Django 4.2 on 2023-04-29 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0005_posts_liked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="liked_by",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
