# Generated by Django 4.2 on 2023-04-30 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0006_alter_posts_liked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="liked_by",
        ),
        migrations.AddField(
            model_name="posts",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_objects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
