import Head from 'next/head'
import { Heading } from '@chakra-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>TweetX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading as="h1" size="4xl" noOfLines={1}>
          TweetX
        </Heading>
      </main>
    </>
  )
}
