# Generated by Django 4.2 on 2023-04-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default="7d170d7362444d9ba3acc5b91d39197d",
                editable=False,
                max_length=30,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
